vich_uploader:
    db_driver: orm

    mappings:
      world_image:
        uri_prefix: /images/worlds
        upload_destination: '%kernel.project_dir%/public/images/worlds'
      item_image:
        uri_prefix: /images/item_image
        upload_destination: '%kernel.project_dir%/public/images/item_image'
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
